# Generated by Django 2.2.5 on 2019-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savetextfilemodel',
            name='fileTXT',
            field=models.FileField(upload_to='documents/', verbose_name='Upload .txt with emails'),
        ),
    ]
